version: '3'

services:
  landing1:
    build: ./landing
    networks:
      - traffic-net

  landing2:
    build: ./landing
    networks:
      - traffic-net

  landing3:
    build: ./landing
    networks:
      - traffic-net

  landing4:
    build: ./landing
    networks:
      - traffic-net

  landing5:
    build: ./landing
    networks:
      - traffic-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traffic-net
    depends_on:
      - landing5
      - landing1
      - landing2
      - landing3
      - landing4
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx:80/stub_status'
    networks:
      - traffic-net
    depends_on:
      - landing5
      - nginx

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - traffic-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - traffic-net 

networks:
  traffic-net:
    driver: bridge


